[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Rafael Juliano <r_juliano@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
